- name: deploy nginx
  hosts: all
  become: yes
  tasks:
    - name: updating repository
      apt:
        update_cache: yes
    - name: install nginx
      apt:
        name: nginx
        state: present
    - name: start nginx
      service:
        name: nginx
        state: started
        enabled: yes